{
 "title": "Node Overview",
 "tags": [ "cassandra" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_endpoint_active, cassandra_cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(cassandra_endpoint_active{cassandra_cluster=\"$cluster\"}, cassandra_node)"
   },
   {
    "name": "thread_pool",
    "label": "Thread Pool",
    "query": "label_values(cassandra_thread_pool_active_tasks{cassandra_cluster=\"$cluster\"}, pool)"
   },
   { "name": "quantile", "label": "Quantile", "query": "0.5,0.75,0.95,0.99" },
   { "name": "topn", "label": "Top 𝑛", "query": "5,10,20" },
   { "name": "table_dashboard_url", "query": "${VAR_TABLE_DASHBOARD_URL}" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(cassandra_endpoint_active{cassandra_cluster=\"$cluster\", endpoint=\"$node\"})"
    }
   ]
  },
  {
   "title": "Client Reads/s",
   "type": "graph",
   "description": "\n### Notes\n\n`casread` is not included, since `read` already includes `casread` values.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\",operation=~\"read|rangeslice\"}[1m])) by (operation)",
     "legendFormat": "Reads ({{operation}})"
    },
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\",operation=~\"read|rangeslice\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Client Writes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_client_request_latency_seconds_count{cassandra_node=\"$node\",operation=~\"write|viewwrite\"}[1m])) by (operation)",
     "legendFormat": "Writes ({{operation}})"
    }
   ]
  },
  {
   "title": "Client Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|rangeslice\"}[1m]) / irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|rangeslice\"}[1m])) by (operation)",
     "legendFormat": "Mean Read Latency ({{operation}})"
    },
    {
     "expr": "max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|rangeslice\", quantile=\"0.95\"}) by (operation)",
     "legendFormat": "p95 Read Latency ({{operation}})"
    },
    {
     "expr": "max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|rangeslice\", quantile=\"0.99\"}) by (operation)",
     "legendFormat": "p99 Read Latency ({{operation}})"
    }
   ]
  },
  {
   "title": "Client Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(irate(cassandra_client_request_latency_seconds_sum{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write|viewwrite\"}[1m]) / irate(cassandra_client_request_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write|viewwrite\"}[1m])) by (operation)",
     "legendFormat": "Mean Write Latency ({{operation}})"
    },
    {
     "expr": "max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write|viewwrite\", quantile=\"0.95\"}) by (operation)",
     "legendFormat": "p95 Write Latency ({{operation}})"
    },
    {
     "expr": "max(cassandra_client_request_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write|viewwrite\", quantile=\"0.99\"}) by (operation)",
     "legendFormat": "p99 Write Latency ({{operation}})"
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by Storage Engine Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Top $topn Tables by Max Reads/s for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|range_read\"}[1m])[$__range:])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Tables by Max Writes/s for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write\"}[1m])[$__range:])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Tables by Max CAS Operations/s for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(irate(cassandra_table_operation_latency_seconds_count{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"cas.*\"}[1m])[$__range:])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Tables by Max q=$quantile Read Latency for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "repeat": "quantile",
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"read|range_read\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Tables by Max q=$quantile Write Latency for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "repeat": "quantile",
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"write\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Tables by Max q=$quantile CAS Operation Latency for Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "repeat": "quantile",
   "targets": [
    {
     "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_operation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", operation=~\"cas.*\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn Tables by Disk Usage for Period",
     "type": "table",
     "description": "_Disk Usage_ includes obsolete SSTables pending garbage collection.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Live Disk Usage for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_live_disk_space_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Live SSTables for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_live_sstables{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by Estimated Partition Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn Tables by Max q=$quantile Estimated Partition Size for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "repeat": "quantile",
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Estimated Partition Size for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Estimated Partition Size for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Estimated Partition Size for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_estimated_partition_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by Tombstones Per Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn Tables by Max q=$quantile Tombstones per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "repeat": "quantile",
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Tombstones per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Tombstones per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile Tombstones per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_tombstones_scanned{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by SSTables Per Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn Tables by Max q=$quantile SSTables Per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "repeat": "quantile",
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile SSTables Per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile SSTables Per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max q=$quantile SSTables Per Read for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_sstables_per_read{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Top $topn Worst Performing Tables by Compaction Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topn Tables by Max Estimated Pending Compactions for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(cassandra_table_estimated_pending_compactions{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[$__range])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    },
    {
     "title": "Top $topn Tables by Max Compaction Bytes Written/s for Period",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "label_join(label_join(topk($topn,max_over_time(irate(cassandra_table_compaction_bytes_written_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[1m])[$__range:])), \"__name\", \".\", \"keyspace\", \"table\"), \"__name\", \":\", \"table_type\", \"__name\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments Pending fsync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_pending_tasks{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}",
       "legendFormat": "Segments"
      }
     ]
    },
    {
     "title": "Segments Written/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_commit_log_completed_tasks_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[1m])",
       "legendFormat": "Segments"
      }
     ]
    },
    {
     "title": "q=$quantile Commit Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "repeat": "quantile",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_commit_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Commit Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_commit_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Commit Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_commit_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Commit Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_commit_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Segment Allocation Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
     "repeat": "quantile",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_segment_allocation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Segment Allocation Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_segment_allocation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Segment Allocation Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_segment_allocation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "q=$quantile Segment Allocation Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cassandra_commit_log_segment_allocation_latency_seconds{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", quantile=~\"$quantile\"}",
       "legendFormat": "Latency"
      }
     ]
    }
   ]
  },
  { "title": "Thread Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$thread_pool Active Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "repeat": "thread_pool",
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "cassandra_thread_pool_active_tasks{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", pool=\"$thread_pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "$thread_pool Blocked Tasks/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "repeat": "thread_pool",
   "yaxes": [
    { "format": "short", "label": "Tasks/s" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_thread_pool_blocked_tasks_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", pool=\"$thread_pool\"}[1m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "$thread_pool Completed Tasks/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "repeat": "thread_pool",
   "yaxes": [
    { "format": "short", "label": "Tasks/s" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_thread_pool_completed_tasks_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\", pool=\"$thread_pool\"}[1m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Buffer Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Pool Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_buffer_pool_size_bytes{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Buffer Pool Misses/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Misses" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_buffer_pool_misses_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[1m])",
       "legendFormat": "Size"
      }
     ]
    }
   ]
  },
  {
   "title": "OS Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "cassandra_os_recent_cpu_load_ratio{cassandra_node=\"$node\"}",
       "legendFormat": "Host Total"
      },
      {
       "expr": "cassandra_process_recent_cpu_load_ratio{cassandra_node=\"$node\"}",
       "legendFormat": "Process"
      }
     ]
    },
    {
     "title": "OS 1 Minute Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_os_1m_load_average{cassandra_node=\"$node\"}",
       "legendFormat": "Load"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_process_open_file_descriptors{cassandra_node=\"$node\"}",
       "legendFormat": "Open File Descriptors"
      },
      {
       "expr": "cassandra_process_maximum_file_descriptors{cassandra_node=\"$node\"}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(cassandra_storage_filesystem_bytes_total{cassandra_node=\"$node\"} - cassandra_storage_filesystem_usable_bytes{cassandra_node=\"$node\"}) / cassandra_storage_filesystem_bytes_total{cassandra_node=\"$node\"}",
       "legendFormat": "{{spec}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_client_native_connections{cassandra_node=\"$node\"}",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Client Authentication Failures/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Failures" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_client_authentication_failures_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[1m])",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "CQL Statements Executed/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_cql_statements_executed_total{cassandra_node=\"$node\"}[1m])",
       "legendFormat": "{{statement_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hints in Progress/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Hints in Progress" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_hints_total{cassandra_node=\"$node\"}[1m])",
       "legendFormat": "{{cassandra_node}}"
      }
     ]
    },
    {
     "title": "Dropped Messages/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_dropped_messages_total{cassandra_cluster=\"$cluster\", cassandra_node=\"$node\"}[5m])",
       "legendFormat": "{{message_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Engine Reads/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_table_operation_latency_seconds_count{cassandra_node=\"$node\",operation=~\"read|range_read\"}[1m])) by (operation)",
       "legendFormat": "Reads ({{operation}})"
      }
     ]
    },
    {
     "title": "Storage Engine Writes/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_table_operation_latency_seconds_count{cassandra_node=\"$node\",operation=\"write\"}[1m])) by (operation)",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Storage Engine CAS Ops/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_table_operation_latency_seconds_count{cassandra_node=\"$node\",operation=~\"cas_.+\"}[1m])) by (operation)",
       "legendFormat": "CAS ({{operation}})"
      }
     ]
    },
    {
     "title": "Estimated Pending Compactions by Strategy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Pending Compactions" }
     ],
     "targets": [
      {
       "expr": "sum(cassandra_table_estimated_pending_compactions{cassandra_node=\"$node\"}) by (compaction_strategy_class)",
       "legendFormat": "{{compaction_strategy_class}}"
      },
      {
       "expr": "sum(cassandra_table_estimated_pending_compactions{cassandra_node=\"$node\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Compactions Bytes Written/s by Strategy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cassandra_table_compaction_bytes_written_total{cassandra_node=\"$node\"}[1m])) by (compaction_strategy_class)",
       "legendFormat": "{{compaction_strategy_class}}"
      },
      {
       "expr": "sum(irate(cassandra_table_compaction_bytes_written_total{cassandra_node=\"$node\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_jvm_memory_pool_used_bytes{cassandra_node=~\"$node\"}",
       "legendFormat": "{{pool}} ({{type}})"
      }
     ]
    },
    {
     "title": "NIO Buffer Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_jvm_nio_buffer_pool_estimated_buffers{cassandra_node=\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "NIO Buffer Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_jvm_nio_buffer_pool_estimated_used_bytes{cassandra_node=\"$node\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "JVM GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_jvm_gc_estimated_collection_duration_seconds_total{cassandra_node=\"$node\"}[1m])",
       "legendFormat": "{{collector}}"
      },
      {
       "expr": "sum(rate(cassandra_jvm_gc_estimated_collection_duration_seconds_total{cassandra_node=\"$node\"}[1m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "JVM GC/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_gc_collection_count{cassandra_node=\"$node\"}[1m])",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_jvm_thread_count{cassandra_node=\"$node\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(cassandra_jvm_thread_count{cassandra_node=\"$node\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "JVM Threads Started/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(cassandra_jvm_threads_started_total{cassandra_node=\"$node\"}[1m])",
       "legendFormat": "Threads"
      }
     ]
    }
   ]
  }
 ]
}